[default.extend-words]
# `typ` is a common Rust convention for avoiding the `type` keyword
typ = "typ"

[default]
# Old wrong spelling support
extend-ignore-re = [
  "alias = \"Cachable\"",
  "old_unique_qualifier_cachable_works",
]

[files]
extend-exclude = [
  "*.md",
  ".git/*",
  "nativelink-proto/*",
  # Contains old wrongly spelt data
  "nativelink-util/tests/data/*.json",
]
ignore-hidden = false
