#:schema ../tools/cargo-with-detailed-deps.json
lints.workspace = true

[package]
edition = "2024"
name = "nativelink-topology"
version = "0.7.10"

[dependencies]
nativelink-config = { path = "../nativelink-config" }
nativelink-scheduler = { path = "../nativelink-scheduler" }
nativelink-service = { path = "../nativelink-service" }
nativelink-store = { path = "../nativelink-store" }
nativelink-util = { path = "../nativelink-util" }

tokio = { version = "1.44.1", features = ["sync"], default-features = false }
tonic = { version = "0.13.0", features = [
  "transport",
], default-features = false }

[dev-dependencies]
nativelink-error = { path = "../nativelink-error" }
