{
  description = "nixception demos — build real packages through the Remote Execution → Nix backend";

  # Pinned to the nixpkgs fork branch that packages nixception v0.5.0:
  #   pkgs.nixception      — the REAPI server (fetched from the released tag)
  #   pkgs.nixceptionHook  — setup hook: starts/stops the server around a build
  #   pkgs.reccStdenv      — stdenv whose cc is recc-wrapped (like ccacheStdenv)
  #
  # Everything here is a *clean* build: no sibling checkouts, no `--impure`.
  # The one requirement is a Nix daemon with recursive-nix enabled (see README).
  inputs = {
    nixpkgs.url = "github:layus/nixpkgs/nixception-hook-shell-mode";
  };

  outputs =
    { self, nixpkgs }:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs { inherit system; };
      inherit (pkgs) lib;

      # ── the one knob ────────────────────────────────────────────────────────
      # Build a package through nixception by swapping its stdenv for reccStdenv.
      # reccStdenv already carries the whole backend wiring: the recc-wrapped
      # compiler, `nixceptionHook` in nativeBuildInputs (starts the server before
      # configurePhase, stops it on exit), and requiredSystemFeatures =
      # ["recursive-nix"]. Every compile — configure probes included — is turned
      # into a Nix derivation, built once, and cached in the Nix store.
      viaNixception = pkg: pkg.override { stdenv = pkgs.reccStdenv; };

      # The slow-compile derivation's source, filtered down to exactly the
      # three files it builds from (Makefile, main.c, slow_table.c) — not
      # gen.py, which only regenerates slow_table.c and is never read at build
      # time. Used as `src` by both the nixception and vanilla slow-compile
      # derivations below, and directly by slow-compile-test.sh: that script
      # builds in this same filtered tree (no separate copy), so what it
      # compiles is by construction the same input the derivations see.
      slowCompileSrc = lib.fileset.toSource {
        root = ./slow-compile;
        fileset = lib.fileset.unions (
          map (f: ./slow-compile + "/${f}") [
            "Makefile"
            "main.c"
            "slow_table.c"
          ]
        );
      };

      # Rename + tag so the demo outputs are easy to spot in `nix build` output
      # and don't collide with the cached upstream package in the store.
      demo =
        name: drv:
        drv.overrideAttrs (old: {
          pname = "nixception-demo-${name}";
          meta = (old.meta or { }) // {
            description = "nixception demo: ${old.pname or name} built through recc + recursive-nix";
          };
        });

      # Bazel demos: nixception driven over gRPC (--remote_executor) instead of
      # through a recc-wrapped compiler. Ports of the workspace bazel-* checks.
      # Returns the nixception targets plus `vanilla-bazel-abseil-cpp` (the same
      # Bazel build with compiles run locally) — that one is peeled off into the
      # `vanilla` baseline set below.
      bazelAll = import ./bazel/demos.nix { inherit pkgs; };
      bazelDemos = lib.filterAttrs (n: _: !lib.hasPrefix "vanilla-" n) bazelAll;

      # reccStdenv demos — build a package by swapping its compiler.
      reccDemos = {
        # GNU Hello (autotools/C). The smallest end-to-end proof: configure
        # probes, one compile, one link — all dispatched to nixception.
        hello = demo "hello" (viaNixception pkgs.hello);

        # spdlog (CMake/C++). Exercises a CMake configure that probes the
        # compiler while the server is up, plus a multi-file C++ build with a
        # real dependency closure (fmt, catch2_3) that the runner must resolve
        # from the store rather than upload. -static-libgcc keeps the bootstrap
        # libgcc out of the output.
        spdlog = demo "spdlog" (
          (viaNixception pkgs.spdlog).overrideAttrs (_: {
            NIX_CFLAGS_COMPILE = "-static-libgcc";
          })
        );

        # zstd (CMake/C). A chunkier C codebase — dozens of translation units —
        # so a cold run vs. a fully-cached rerun is visibly different.
        zstd = demo "zstd" (viaNixception pkgs.zstd);

        # One deliberately expensive translation unit: a checked-in C file
        # (slow-compile/slow_table.c, generated by gen.py) with a ~550k-element
        # *designated* aggregate initializer, which GCC parses super-linearly
        # (~5s at -O2). reccStdenv routes that compile to nixception; the
        # second build is served from the Nix store in milliseconds. The
        # clearest before/after of the whole point — run it, `nix run
        # .#cleanup`, run it again, compare the timing summaries. slow_table.c
        # is static (not regenerated at build time) so every build — and
        # slow-compile-test.sh's cross-environment comparison — compiles
        # byte-identical input.
        slow-compile = pkgs.reccStdenv.mkDerivation {
          pname = "nixception-demo-slow-compile";
          version = "1";
          src = slowCompileSrc;
          enableParallelBuilding = true;
          makeFlags = [ "CFLAGS=-O2" ];
          installPhase = ''
            runHook preInstall
            mkdir -p "$out/bin"
            cp slow_demo "$out/bin/"
            "$out/bin/slow_demo"
            runHook postInstall
          '';
          meta.description =
            "nixception demo: a 5-second GCC compile (huge designated initializer) routed through recc";
        };
      };

      # Every demo, both kinds. `nix build .#<name>` / `nix flake check`.
      demos = reccDemos // bazelDemos;

      # Baselines: the plain upstream package, built the ordinary way — no
      # nixception, no reccStdenv, no recursive-nix. `nix build .#vanilla-<name>`
      # to time the normal build against its nixception counterpart, or just to
      # have the reference binary. Straight `pkgs.<name>` from the pinned
      # nixpkgs, so most are already a binary-cache hit. Not touched by
      # `nix run .#cleanup`.
      vanillaSources = {
        hello = pkgs.hello;
        spdlog = pkgs.spdlog;
        zstd = pkgs.zstd;
        # Upstream abseil-cpp (CMake) — the baseline for the bazel-abseil-cpp
        # demo, which builds the same library via Bazel + rules_nixpkgs.
        abseil-cpp = pkgs.abseil-cpp;
        slow-compile = pkgs.stdenv.mkDerivation {
          pname = "vanilla-slow-compile";
          version = "1";
          src = slowCompileSrc;
          enableParallelBuilding = true;
          makeFlags = [ "CFLAGS=-O2" ];
          installPhase = ''
            runHook preInstall
            mkdir -p "$out/bin"
            cp slow_demo "$out/bin/"
            "$out/bin/slow_demo"
            runHook postInstall
          '';
          meta.description = "baseline: the slow-compile demo built with a plain local compiler";
        };
      };
      vanilla =
        lib.mapAttrs' (n: v: lib.nameValuePair "vanilla-${n}" v) vanillaSources
        # The Bazel baseline is already `vanilla-*`-named (and needs
        # recursive-nix, unlike the others), so merge it in as-is.
        // lib.filterAttrs (n: _: lib.hasPrefix "vanilla-" n) bazelAll;

      # `nix run .#cleanup` — drop the nixception REAPI action cache and the
      # demo build outputs from the Nix store, so the next `nix build` is a true
      # cold run. Mirrors `workspace/justfile`'s clean-store, trimmed to what the
      # demos touch: the `-reapi-*` paths (content-addressed action cache) and
      # the `nixception-demo-*` build outputs. Deletes in batches because
      # freeing an action output makes its `-reapi-adapted` inputs collectable.
      # Pass -g / --gc to also run `nix-collect-garbage` afterwards (frees the
      # now-dead Bazel dependency closures — slower).
      cleanup = pkgs.writeShellApplication {
        name = "nixception-demo-cleanup";
        runtimeInputs = [ pkgs.fd pkgs.nix ];
        text = ''
          run_gc=0
          case "''${1:-}" in
            -g | --gc) run_gc=1 ;;
            "") ;;
            *) echo "usage: nix run .#cleanup [-g|--gc]" >&2; exit 2 ;;
          esac

          # A stray ./result* symlink from an earlier `nix build` is a GC root:
          # it keeps that output (and everything it references, including its
          # reapi-action) alive no matter what we delete below. Drop them first.
          rm -f ./result ./result-*

          # Delete every /nix/store top-level entry whose name matches a glob,
          # in batches: freeing an action output makes its -reapi-adapted inputs
          # collectable on the next pass. `fd` rejects patterns containing "/",
          # so match on the name with --glob, never a regex with a char class.
          delete_glob() {
            local glob="$1" paths n del
            while true; do
              paths="$(fd --maxdepth 1 --glob --exclude '*.lock' -- "$glob" /nix/store 2>/dev/null || true)"
              [ -n "$paths" ] || break
              n="$(printf '%s\n' "$paths" | wc -l)"
              del="$(printf '%s\n' "$paths" | xargs nix-store --delete 2>&1 \
                | grep -c "^deleting '" || true)"
              echo "  $glob: $n found, $del deleted"
              [ "$del" -eq 0 ] && break
            done
          }

          echo "Dropping the nixception REAPI action cache..."
          delete_glob '*-reapi-action'
          delete_glob '*-reapi-action.drv'
          delete_glob '*-reapi-adapted'

          echo "Dropping demo build outputs..."
          delete_glob '*-nixception-demo-hello-*'
          delete_glob '*-nixception-demo-spdlog-*'
          delete_glob '*-nixception-demo-zstd-*'
          delete_glob '*-nixception-demo-slow-compile-*'
          delete_glob '*-nixception-demo-bazel-hello-world'
          delete_glob '*-nixception-demo-bazel-hello-world.drv'
          delete_glob '*-nixception-demo-bazel-abseil-cpp'
          delete_glob '*-nixception-demo-bazel-abseil-cpp.drv'
          delete_glob '*-nixception-demo-slow-bazel'
          delete_glob '*-nixception-demo-slow-bazel.drv'

          remaining="$(fd --maxdepth 1 --glob --exclude '*.lock' -- '*-reapi-*' /nix/store 2>/dev/null | wc -l)"
          echo "Remaining reapi paths: $remaining"

          if [ "$run_gc" = 1 ]; then
            echo "Collecting garbage (dead Bazel dep closures)..."
            nix-collect-garbage
          fi
        '';
      };

    in
    {
      packages.${system} = demos // vanilla // {
        default = demos.hello;

        # `nix build .#all` — the reccStdenv demos in one go. Bazel demos are
        # heavy (each pulls a Bazel dependency closure); build those by name.
        all = pkgs.symlinkJoin {
          name = "nixception-demos-all";
          paths = lib.attrValues reccDemos;
        };

        inherit cleanup;
      };

      # `nix run .#cleanup [-- -g]`
      apps.${system}.cleanup = {
        type = "app";
        program = "${cleanup}/bin/nixception-demo-cleanup";
      };

      # `nix flake check` — every demo (reccStdenv + Bazel) and every vanilla
      # baseline.
      checks.${system} = demos // vanilla;

      # `nix develop` — a shell to poke at nixception by hand, outside any
      # sandbox. `nixceptionHook` in nativeBuildInputs starts the server
      # automatically when the shell is entered (its setup hook detects
      # $IN_NIX_SHELL and appends to $shellHook instead of a build phase — the
      # same server lifecycle reccStdenv gets in a real build, minus the
      # recursive-nix requirement: shell mode talks to the ambient Nix daemon)
      # and stops it on exit. recc is already pointed at it via RECC_SERVER.
      devShells.${system}.default = pkgs.mkShell {
        packages = [
          pkgs.buildbox # provides `recc`
          pkgs.gcc
        ];
        nativeBuildInputs = [ pkgs.nixceptionHook ];
        env = {
          RECC_SERVER = "127.0.0.1:50051";
          RECC_CAS_SERVER = "127.0.0.1:50051";
          RECC_ACTION_CACHE_SERVER = "127.0.0.1:50051";
          RECC_INSTANCE = "main";
          RECC_VERBOSE = "1";
        };
        shellHook = ''
          echo "nixception demo shell — server starts automatically, see above"
          echo "  route a build: recc gcc -c -O2 -o out.o in.c"
        '';
      };
    };
}
